name: worldwarp
main: lovetwice1012\worldwarp\Main
version: 1.0.0
api: 3.12.0
auther: lovetwice1012

commands:
  wwarp:
    description: Select a destination in the world in the form to teleport.
    usage: /wwarp
